@startuml

title Forward Proxy

skinparam backgroundColor lightGray

participant Browser
boundary ForwardProxy as "Forward Proxy"
entity Google

Browser -> ForwardProxy : Request for google.com
ForwardProxy -> Google : Proxy Request for google.com
Google -> ForwardProxy : Response to proxied request
ForwardProxy -> Browser  : Forward response from proxied request

@enduml
