@startuml

skinparam backgroundColor lightGray

participant Browser
boundary ReverseProxy as "Reverse Proxy"
entity HiddenServer as "Hidden Server"

Browser -> ReverseProxy : Request for back-end data
ReverseProxy -> HiddenServer : Forward request to hidden server
HiddenServer -> ReverseProxy : Response with back-end data
ReverseProxy -> Browser : Proxy response from forwarded request

@enduml
